id: A7EB5D313
title: Toh_207-Strength_of_the_Elephant-v2
type: translation
pechas:
- I24BBEBF8
- I26C960FE
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-062-007
  eft-text-version: 1.1.5 2020
  title: Toh_207-Strength_of_the_Elephant-v2
alignment_to_base:
  I24BBEBF8/C34A: B482
  I26C960FE/BA34: B482
